### ISSUE TITLE
Can't rerender

### ISSUE THREAD

**Issue by kmod** [conda-forge/mpi4py-feedstock#53]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I try to rerender I get the following:

```
$ conda-smithy rerender
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2022.03.28.19.38.17
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpvk64f_b0
INFO:conda_smithy.configure_feedstock:pypy37-windows.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:pypy37.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:python310.yaml from feedstock is ignored and upstream version is used
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /tmp/tmpvk64f_b0/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmpvk64f_b0/conda_build_config.yaml
Adding in variants from /home/kmod/pyston/mpi4py-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /home/kmod/pyston/mpi4py-feedstock/recipe/conda_build_config.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpvk64f_b0/share/conda-forge/migrations/pypy37.yaml,/tmp/tmpvk64f_b0/share/conda-forge/migrations/pypy37-windows.yaml,/tmp/tmpvk64f_b0/share/conda-forge/migrations/python310.yaml
Adding in variants from argument_variants
INFO:conda_build.variants:Adding in variants from argument_variants
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpvk64f_b0/share/conda-forge/migrations/pypy37.yaml,/tmp/tmpvk64f_b0/share/conda-forge/migrations/pypy37-windows.yaml,/tmp/tmpvk64f_b0/share/conda-forge/migrations/python310.yaml
Traceback (most recent call last):
  File "/home/kmod/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 681, in main
    args.subcommand_func(args)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 491, in _call
    configure_feedstock.main(
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2262, in main
    render_travis(env, config, forge_dir, return_metadata=True)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 1155, in render_travis
    return _render_ci_provider(
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 758, in _render_ci_provider
    dump_subspace_config_files(
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 431, in dump_subspace_config_files
    configs, top_level_loop_vars = _collapse_subpackage_variants(
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 375, in _collapse_subpackage_variants
    break_up_top_level_values(top_level_loop_vars, used_key_values),
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 199, in break_up_top_level_values
    sort_config(squished_variants, zip_key_groups)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 127, in sort_config
    for pin in list(reversed(sorted(pkg_pins.keys()))):
AttributeError: 'str' object has no attribute 'keys'
```

The value of `pkg_pins` is `'x.x'`. I'm not super familiar with this whole system, but maybe you need some dashes in the conda_build_config.yaml file so that it gets interpreted as a list? Just a guess.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by dalcinl** [comment]
You should report this issue to @conda-forge/conda-smithy and ask for help there. We recipe maintainers do not have control on the rerender process (unless we have a bug in `conda_build_config.yaml`).

**Comment by kmod** [comment]
Hi, unfortunately I can't access that link.

I don't know enough whether to say that the current situation is a bug in conda_build_config.yaml, but I'll put up a draft PR with a change to that file that causes the rerender to succeed. Hopefully that better describes what I'm getting at, and then we can determine if it's a bug in the yaml or in conda-smithy.

**Comment by leofang** [comment]
It is almost always a bug in conda-smithy: https://github.com/conda-forge/conda-smithy Please help us file an issue there because this is apparently a regression (which I can reproduce locally), thanks!

**Comment by kmod** [comment]
Sure thing, I filed it as https://github.com/conda-forge/conda-smithy/issues/1615

I did my best to convey your points, but I don't personally have the context to know that this is a bug in conda-smithy so they might ask you to chime in.

**Comment by leofang** [comment]
Thanks, @kmod. I replied in the issue. It's a bug in conda-smithy.
